### ISSUE TITLE
Arbitrary distribution recurrence relation

### ISSUE THREAD

**Issue by mjc239** [mjc239/mjc239.github.io#10]

**Comment by blujay92** [comment]
Looks quality. Like the Note box thing.

**Comment by blujay92** [comment]
Maybe it could say something like "we may take" since there is potentially some choice for the optimal thresholds. Not super important though.

**Comment by blujay92** [comment]
Oops sorry this was meant to be a comment on #11

**Comment by blujay92** [comment]
I noticed that you mentioned that the simplification of phi to a single integral doesn't require non-negativity, I'd be interested to know what the simplest explanation for why tFbar(t) goes to zero as t goes to zero in that case. Just out of curiosity.

**Comment by blujay92** [comment]
Also given that I think we both agree that the single integral one is most useful, and since that doesn't require non-neg, is there a different way of presenting the two versions?

I'm not sure whether putting the other one second makes it seem like it's perhaps more or as important, whereas I personally think that that one is more of a curiosity.

**Comment by mjc239** [comment]
> I noticed that you mentioned that the simplification of phi to a single integral doesn't require non-negativity, I'd be interested to know what the simplest explanation for why tFbar(t) goes to zero as t goes to zero in that case. Just out of curiosity.

This integration by parts doesn't rely on positivity of the prices:

![IMG_20210122_004259](https://user-images.githubusercontent.com/17711185/105430225-f1dc1600-5c4a-11eb-98e5-cde396cae1c2.jpg)

so we only need pFbar(p) -> 0 as p -> infinity. If we do assume positivity, then by the Markov inequality this is definitely at least finite. Is there a way of saying this must be equal to zero, or do we need a further condition on the pdf?

**Comment by blujay92** [comment]
I thought we had a conversation about this ages ago? You can get it using 2nd moment Markov thing, or indeed a 1+\eps moment provided you have one.

However, I'm pretty sure you can show that Fbar(t) = o(1/t) even if all you have is a 1st moment. I was asking because I thought from how you wrote it that you had a cleaner way of getting this out?

**Comment by blujay92** [comment]
I was kind of hoping you did tbh because this kind of got on my nerves a bit

**Comment by blujay92** [comment]
file:///C:/Users/User/AppData/Roaming/Signal/attachments.noindex/ed/ed67b881d58da921a72e608fe63c6a4872e2db592ec982dd22814e076d63a9c9

This was the rough argument I had for why finite mean gives the little oh version, but I must admit I feel a bit uneasy about the whole thing because while it seems straightforward I have this feeling that if this was a thing I'd have came across it before.

**Comment by mjc239** [comment]
Oh yes, I think I do remember - if the prices are non-negative, and the second moment exists and is finite, then the 2nd-moment Markov inequality is sufficient. There are distributions with finite mean but infinite variance (e.g. Pareto) where it's not sufficient
