### ISSUE TITLE
Arbitrary distribution - continuous/discrete cases

### ISSUE THREAD

**Issue by mjc239** [mjc239/mjc239.github.io#12]
Review of these sections

**Comment by blujay92** [comment]
I have nothing to say about the discrete case.

**Comment by blujay92** [comment]
To be totally frank I haven't been thinking about discrete at all. I'm not sure whether the bit where we say we assume cts needs to be a bit earlier. For example, if cdf is at most not less than the stuff in "Arbitrary (non-negative) turnips: a recurrence" needs to be cts does it not?

Or at least I'm a bit confused why there's a section who's title makes it sound like it's general which makes reference to a pdf, but otherwise is purely stated in terms of expectations and probabilities and then is followed by two sections about cts and discrete separately as if the previous one wasn't.

**Comment by blujay92** [comment]
Obvs the thing about < vs <= is splitting hairs a bit but I do find it a bit confusing that it mentions pdf if it's supposed to be general (and if it's not then that wasn't obvious to me).

I get that Non-negative Turnips says pdf, but I think it's confusing to then have a subsection called cts. Could that section just be entitled something to with phi and then the discrete one can just be discrete as is.

**Comment by blujay92** [comment]
You could even say in the discrete one what the general recursion would be if you want, but up to you.
