### ISSUE TITLE
Bounds in uniform case

### ISSUE THREAD

**Issue by mjc239** [mjc239/mjc239.github.io#8]
Review/formatting of derivation of upper/lower bounds for uniform case

**Comment by mjc239** [comment]
I think the content of this section is good to go, it may be worth going through it to check on the formatting (for clarity of reading), and whether there needs to be any expansions of any sections.

**Comment by blujay92** [comment]
Decided to rename it the uniform turnips constant.

**Comment by blujay92** [comment]
There are certain paragraphs that aren't looking too good when I half screen them on my laptop because the inline bits are then too wide. I expect they wouldn't look the best on mobile for similar reasons, but short of having different options for each, or basically displaying anything I don't know that there's a lot we can do.

**Comment by blujay92** [comment]
Flipped the sign of this named constant as in hindsight it's fairly clear that it's got to be negative by considering the size of the infinite sum as compared to the Euler-Mascheroni constant.

**Comment by mjc239** [comment]
A useful trick for viewing as a mobile - press F12 to go into developer mode, then click on this button:
![image](https://user-images.githubusercontent.com/17711185/104660388-57198f80-56be-11eb-820c-be0b46250f8f.png)

**Comment by mjc239** [comment]
doesn't seem to look too bad on mobile, as far as I can see at least

**Comment by blujay92** [comment]
Okay cheers!
